import os
import cv2
import numpy as np
import imageio
from tqdm import tqdm


import pickle
from pathlib import Path

def load_replay_data(path):
    """Load saved replay data file generated by new_model_eval."""
    path = Path(path)
    with open(path, "rb") as f:
        data = pickle.load(f)
    print(f" Loaded replay data from: {path}")
    return data['trajectories'], data.get('env_name', None), data.get('config', None), data.get('ant_env_config', None)




class VideoCreatorReplay:
    """
    Offline video creator that replays recorded trajectories to visualize
    Meta-RL agent behavior (e.g., ANT executing tasks inferred from Toy module).

    Does NOT re-run policy or encoder. It uses precomputed trajectories
    and environment renderings for faithful reproduction of actual behavior.
    """

    def __init__(self, fps=30, width=640, height=480, font_scale=0.6, font_color=(255, 255, 255), thickness=1):
        self.fps = fps
        self.width = width
        self.height = height
        self.font = cv2.FONT_HERSHEY_SIMPLEX
        self.font_scale = font_scale
        self.font_color = font_color
        self.thickness = thickness

    def create_video_from_trajectories(
        self,
        env,
        trajectories,
        save_as="./videos/replay.mp4",
        max_frames=None,
        show_info=True,
        overlay_latent=True,
        overlay_goal=True,
        overlay_reward=True,
        overlay_position = True
    ):
        """
        Replays given trajectories and generates a rendered video.

        Parameters
        ----------
        env : gym.Env or MetaEnv
            Mujoco environment used for rendering.
        trajectories : List[Dict]
            Rollout data, each dict containing 'observations', 'actions', 'rewards', 'tasks', etc.
        save_as : str
            Output video path (mp4).
        max_frames : int, optional
            Max total frames to render (if None, render all).
        show_info : bool, optional
            Whether to overlay textual information.
        overlay_latent, overlay_goal, overlay_reward : bool, optional
            Whether to display corresponding info on the frames.
        """
        os.makedirs(os.path.dirname(save_as), exist_ok=True)
        writer = imageio.get_writer(save_as, fps=self.fps)

        total_frames = 0
        print(f" Generating replay video at {self.fps} FPS ...")

        for traj_id, traj in enumerate(trajectories):
            print(f"Replaying trajectory {traj_id+1}/{len(trajectories)} ...")

            obs = env.reset()
            actions = traj["actions"]
            rewards = traj.get("rewards", np.zeros(len(actions)))
            latent = traj.get("latent_mean", None)
            tasks = traj.get("tasks", None)

            for t, action in enumerate(actions):
                step_result = env.step(action)
                if len(step_result) == 5:
                    obs, reward, terminated, truncated, info = step_result
                    done = terminated or truncated
                else:
                    obs, reward, done, info = step_result



                # ---- render ----
                frame = None
                try:
                    frame = env.render(mode="rgb_array", width=self.width, height=self.height)
                except TypeError:
                    try:
                        frame = env.render('rgb_array')
                    except Exception:
                        frame = env.render()

                # resize fallback
                if frame.shape[1] != self.width or frame.shape[0] != self.height:
                    frame = cv2.resize(frame, (self.width, self.height))
                # Overlay text
                if show_info:
                    overlay = frame.copy()
                    y0 = 25
                    lines = [f"Trajectory: {traj_id+1}", f"Step: {t+1}"]

                    if overlay_reward:
                        r = reward if not np.isnan(reward) else 0.0
                        lines.append(f"Reward: {r:.3f}")

                    if overlay_goal and tasks is not None:
                        goal = tasks[t]["goal"] if isinstance(tasks[t], dict) and "goal" in tasks[t] else None
                        if goal is not None:
                            lines.append(f"Goal: {np.round(goal, 3)}")

                    # 显示当前 Ant 的横向位置
                    if overlay_position and hasattr(env, "sim"):
                        try:
                            x_pos = float(env.sim.data.qpos[0])
                            lines.append(f"Position: {x_pos:.2f} m")
                        except Exception:
                            pass

                    for i, line in enumerate(lines):
                        cv2.putText(
                            overlay,
                            line,
                            (10, y0 + i * 20),
                            self.font,
                            self.font_scale,
                            self.font_color,
                            self.thickness,
                            cv2.LINE_AA,
                        )
                    frame = cv2.addWeighted(overlay, 0.9, frame, 0.1, 0)

                writer.append_data(frame[..., ::-1])  # RGB→BGR fix for imageio

                total_frames += 1
                if max_frames is not None and total_frames >= max_frames:
                    print("Reached max frame limit.")
                    writer.close()
                    return

                if done:
                    obs = env.reset()

        writer.close()
        print(f"Video saved at: {save_as} ({total_frames} frames total)")
